### ISSUE TITLE
Unable to resize VM disks

### ISSUE THREAD

**Issue by tzerod** [xcp-ng/xenadmin#114] opened 2018-10-29 13:53 UTC
Reference: https://xcp-ng.org/forum/topic/533/unable-to-resize-vm-disks/8

When resizing VM disks,  most return an error of "The disk size cannot be altered as the disk is already being updated." even with the VM shutdown. Detaching the disks from the VM does not help.  

Using "XE vdi-resize..... " from the command line works great.  

If I move the VM disk from one iSCSI SR to another,  then Xenadmin can resize without problem.

**Comment by borzel** [comment] 2018-11-08 20:32
@tzerod I can not reproduce the issue:
* created a VM on iSCSI-SR
* resized disk successfully
* copied VM
* resized disk of that copied VM successfully

any pointers?

**Comment by tzerod** [comment] 2018-11-09 17:22
Below is a screenshot I took this morning.  As you can see, the VM is shutdown.  And yet I am unable to resize the disk.  Do you want me to try a different version of XCP-ng Center?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tzerod** [comment] 2018-11-09 18:40
Just tried XCP-ng Center 7.6, problem still exists.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by borzel** [comment] 2018-11-09 19:14
@tzerod there is no screenshot. Please don't use email to send screenshots to github :-)

Hmm... what can we do to resolv the issue? Can you reproduce the situation with a new VM and provide the steps?

**Comment by borzel** [comment] 2018-11-10 18:14
@tzerod there is a possibility to get your issue reproduced here on my dev pc. 

### But only if you dont't mind to give me your pool-database.

https://github.com/xcp-ng/xcp/wiki/Systemfiles#xapi-database

Copy that file and upload it to my nextcloud server at: https://schulzalex.de/nextcloud/index.php/s/pbA9RdKrzpGA4m9

**Comment by tzerod** [comment] 2018-11-14 20:10
File has been uploaded,  sorry for the delay

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cocoon** [comment] 2018-11-22 07:05
Hi tzerod,
can you tell more about the environment like:

- Hardware for the XCP-NG Server
- ISCSI-Storage is served from Hardware/Software like HNAS/NetApp/FreeNAS/Windows...

At least it looks like a single node with pool, so no HA is involved. Had it once that the VM started automatically after I had shutdown the VM to increase the disk. But yours is still shutdown.

**Comment by borzel** [comment] 2018-12-25 22:36
@tzerod your VDI (I tested the disk from the OpenVPN VM) has not the needed flag `resize` or `resize_online` in the `Allowed Operations`

So it's a metadata issue on your host. But I don't know how to resolve this. Maybe someone on the forum has more knowledge about this :-/

![grafik](https://user-images.githubusercontent.com/5782951/50427025-dd2ac980-089c-11e9-94d4-704e6311c51c.png)

**Comment by borzel** [comment] 2018-12-25 22:40
Becaus of this, I close this issue. Please reopen if needed!

**Closed by borzel** 2018-12-25 22:40 UTC
Labels: have to be checked
