### ISSUE TITLE
XCP-ng Center not working following new/clean install of XCP-ng v8

### ISSUE THREAD

**Issue by LoVoltage** [xcp-ng/xenadmin#175] opened 2019-09-20 18:22 UTC
**Issue:**

XCP-ng Center is not able to connect to XCP-ng server after a new or clean install (not upgrade) of XCP-ng v8.

![Screenshot from 2019-09-22 17-47-37](https://user-images.githubusercontent.com/51893248/65394906-3c046d00-dd61-11e9-89f9-62eb1019d1a7.png)

**Error:**
**_Windows 7 and Server 2008 R2_**
- Error message “**_Unable to connect to the server {server IP address}. Could not create secure SSL/TLS channel"_**
- When opening the XCP-ng Center, an error is displayed after a long delay

**_Windows 10_**
- XCP-ng center cannot connect to the designated server with the error message “**_Unable to 
  connect to server {server IP address}. Could not find a server on {server IP address}. Check that 
  XCP-ng is configured correctly on {server IP address} and try again."_**
- When opening the XCP-ng Center, an error is displayed after a long delay

![Screenshot from 2019-09-20 15-58-09](https://user-images.githubusercontent.com/51893248/65355267-91087d80-dbbf-11e9-89bf-49a393cd8bc2.png)

**XCP-ng Server Issue:**
At the XCP-ng console, selecting "**_Status DIsplay_**" , the SSL key fingerprints are displayed.
- **HTTPS key is not present**
- SSH key is present
**- When pointing a web browser to the IP of the XCP-ng server, the landing page is not displayed**

![Screenshot from 2019-09-22 17-21-37](https://user-images.githubusercontent.com/51893248/65395133-a074fb80-dd64-11e9-982a-aefc890d3e9f.png)

**Workaround:**
Installed XCP-ng 7.6, applied latest updates, then upgraded to v8 and applied latest updates. Was able to successfully access the XCP-ng Center with out error

**XCP-ng Server Installation:**
- Dell Poweredge R710
- XCP-ng v8 obtained from main XCP-ng site
- Verified hash
- Written to USB flash drive
- HDDs with no existing partitions including **_no Dell utility partition_**
- Static IP for management interface
- Installation completes without error messages, hangs or other issues

**Troubleshooting:**
- Verified ability for connectivity from the XCP-ng server to the XCP-ng Center host
- No firewall rules were impeding traffic using server FQDN or IP address
- Installing various versions of XCP-ng Center did not correct the issue
- Reinstallation of XCP-ng v8 did not correct the issue; **Issue duplication**
**From the XCP-ng console, commands to recreate the SSL certificate and restart the service failed**

**It seems the issue is with XCP-ng v8 when installing new or clean**

**Comment by schulz-alexander** [comment] 2019-09-21 07:38
Did you try to install XCP-ng Center on another PC? Just to be sure there is no issue with the used client PC.

**Comment by LoVoltage** [comment] 2019-09-21 15:49
> Did you try to install XCP-ng Center on another PC? Just to be sure there is no issue with the used client PC.

Yes. Installed Center on multiple physical and virtual Windows OSs including 7, 8.x, 10, Server 2008 R2, Server 2016

No issues accessing XCP-ng servers running 7.6.x or 8.0 upgrades from 7.6. The issue is accessing new or clean XCP 8 installs. 

Because of this, we believe the issue is some where in XCP, not in Center.

**Comment by schulz-alexander** [comment] 2019-09-22 07:56
Do you use proxy servers for web browsing?

**Comment by LoVoltage** [comment] 2019-09-22 19:12
> Do you use proxy servers for web browsing?

No. None of the sites containing XCP-ng or Center use a proxy.

**Comment by schulz-alexander** [comment] 2019-09-22 20:38
Hmm... so there must be something on the XCP-ng server side, as you said. :-/

**Comment by LoVoltage** [comment] 2019-09-22 21:40
**Addional testing of XCP-ng V8 new/clean install**

At the XCP-ng console, selecting "Status DIsplay" , the SSL key fingerprints are displayed. 
- **HTTPS key is not present**
- SSH key is present

![Screenshot from 2019-09-22 17-21-37](https://user-images.githubusercontent.com/51893248/65394703-242be980-dd5f-11e9-9bb7-d17cbf8621d2.png)

This supports our theory that the issue is with XCP not Center

**Additional:** 
Opening a web browser (Chrome) and entering the IP address of the XCP-ng Server pulls a landing page with external links to get the XOA. Tried to access this landing page on the XCP v8 clean/new install, but it's blank with the error " _This site can’t be reached http://server IP/ is unreachable.
ERR_ADDRESS_UNREACHABLE_"

Tried using HTTP and HTTPS, both with the same result

**Comment by LoVoltage** [comment] 2019-09-22 21:42
Reopening issue in XCP
https://github.com/xcp-ng/xcp/issues/275

**Comment by schulz-alexander** [comment] 2020-01-26 17:53
As the issue is also present with XO/XOA I close this issue here.

**Closed as completed by schulz-alexander** 2020-01-26 17:53 UTC

**Comment by ghost** [comment] 2020-04-03 06:34
It is not related to this issue but when I searched for my issue, I landed here.
So I am linking this thread for people who will be in the same case as me when upgrading from 8.0 to 8.1 via yum (the ISO will be patched by the XCP-ng team soonish as I understood)
https://xcp-ng.org/forum/topic/2797/xcp-ng-8-1-clean-install-missing-stunnel4/62
