### ISSUE TITLE
XCP-ng Center 8.0.0 (build 8.0.0.24) live/offline virtual migration/move

### ISSUE THREAD

**Issue by gorbi13G** [xcp-ng/xenadmin#156] opened 2019-05-20 06:40 UTC
**Describe the bug**
Impossible to do Live or offline migration/move of virtual from one Xen to another one.

**To Reproduce**
Start XenCenter
1. Right click to one virtual
2. While migrating first virtual after XenCenter startup:Select destination Xen, select all necessary options to migrate.. it works
3. While trying to migrate 2nd virtual, when select dest.Xen, button Next is grayed out, not possible to continue

**Expected behavior**
Buttno next should be black and i we can continue with live/offline migration/move of a virtual to another Xen.

**Comment by d4v1dm013** [comment] 2019-05-20 14:09
I confirm this issue.

I just update my XenCenter and I can't Move/Live Migrate any VM.

You can see the problem described in my screenshot.

![screenshot-2019-05-20-160638](https://user-images.githubusercontent.com/21315179/58027667-7216b380-7b19-11e9-9583-53add9344853.jpg)

**Comment by olivierlambert** [comment] 2019-05-20 14:15
Can you confirm it's specific to XCP-ng Center and not the platform? Does it work well in Xen Orchestra?

**Comment by gorbi13G** [comment] 2019-05-20 14:20
before upgrade or from another machine where is still XCP-ng Center 7.6.3.21 it is still working OK...

**Comment by d4v1dm013** [comment] 2019-05-20 14:23
> 
> 
> Can you confirm it's specific to XCP-ng Center and not the platform? Does it work well in Xen Orchestra?

I don't have Xen Orchestra but I can tell you that with another XenCenter 7.6.3, I don't have any issue. 

It seems that when we select the destination, a check is made and the "Next" field becomes available if all is OK, obviously on the 8.0.0.24 version, the field remains disabled. This seems to come directly from the interface.

**Comment by olivierlambert** [comment] 2019-05-20 14:25
I'd like to have a double check confirmation if possible, in order to triage and make a better diag. You have two options:

* migration using `xe` in CLI
* Using XOA Free which is pretty straightforward to deploy with a `bash -c "$(curl -s http://xoa.io/deploy)"` from your host console/SSH

**Comment by d4v1dm013** [comment] 2019-05-20 14:28
> 
> 
> I'd like to have a double check confirmation if possible, in order to triage and make a better diag. You have to options:
> 
>     * migration using `xe` in CLI
> 
>     * Using XOA Free which is pretty straightforward to deploy with a `bash -c "$(curl -s http://xoa.io/deploy)"` from your host console/SSH

Ok, i will make a migration via CLI and i will post the result to you

**Comment by schulz-alexander** [comment] 2019-05-20 15:42
Be aware that there is no XenCenter 7.6.3!!!

**Comment by d4v1dm013** [comment] 2019-05-20 15:47
> Be aware that there is no XenCenter 7.6.3!!!

The version is 7.6.3,and it is XCP-ng Center of course  :)

**Comment by d4v1dm013** [comment] 2019-05-20 15:58
![Annotation 2019-05-20 174404](https://user-images.githubusercontent.com/21315179/58035341-d7be6c00-7b28-11e9-8b01-c07f396dcf11.jpg)

**Comment by d4v1dm013** [comment] 2019-05-21 07:31
I confirm that the following command work with any issue: 

```xe vm-migrate vm=xxx remote-master=xxx remote-username=xxx remote-password=xxx vif:xx=xxx live=true```

So i thing it's just a bug from the XCP-ng Center.

Thanks for your assistance

**Comment by gorbi13G** [comment] 2019-05-21 07:44
100% this is bug of the new XCP-ng Center 8.0.0 (build 8.0.0.24) First migration/movement after application start is working like a charm - button Next is not grayed out. In the second migration is usually the "Next" button grayed out.

**Comment by olivierlambert** [comment] 2019-05-21 07:51
Thanks for the feedback lads!

**Comment by schulz-alexander** [comment] 2019-05-21 17:38
I can reproduce the issue.

**Comment by schulz-alexander** [comment] 2019-05-21 18:13
Found it: https://github.com/xenserver/xenadmin/commit/273c9f339422fb6dab71b135491b4176f58659c8

**Comment by olivierlambert** [comment] 2019-05-21 18:15
I don't get it (reading C# code isn't my main talent). Why it was introduced and why it causes an issue for us?

**Comment by schulz-alexander** [comment] 2019-05-21 18:23
It's seems to be also an issue in XenCenter 8.0 and only fixed in xenadmin master. It's maybe a regression, but I don't have access to the internal CITRIX isseu tracker, so I can not know what's CA-314346 :-/

**Comment by olivierlambert** [comment] 2019-05-21 18:23
haha so it's an upstream bug then :p Nice catch!

**Comment by schulz-alexander** [comment] 2019-05-21 18:27
@gorbi13G @d4v1dm013 
Here I have a debug build, please test if it resolves your issue: [XCP-ng_Center_8.0.0.24plus_Debug.zip](https://github.com/xcp-ng/xenadmin/files/3203935/XCP-ng_Center_8.0.0.24plus_Debug.zip)

**Comment by schulz-alexander** [comment] 2019-05-21 18:30
@olivierlambert have a look at the last known issue and laugh loud: https://docs.citrix.com/en-us/citrix-hypervisor/whats-new/known-issues.html

**Comment by d4v1dm013** [comment] 2019-05-22 07:14
> 
> 
> @gorbi13G @d4v1dm013
> Here I have a debug build, please test if it resolves your issue: [XCP-ng_Center_8.0.0.24plus_Debug.zip](https://github.com/xcp-ng/xenadmin/files/3203935/XCP-ng_Center_8.0.0.24plus_Debug.zip)

Hi, i have just tested your version, the problem is solved.

**Comment by gorbi13G** [comment] 2019-05-22 10:22
When will be released some fixed version - i know plus_debug.zip is some fixed version..but something more official to download in releases..?

**Comment by schulz-alexander** [comment] 2019-05-22 22:35
ASAP .... maybe in the next 2 weeks

**Closed as completed** 2019-05-22 22:35 UTC

**Comment by schulz-alexander** [comment] 2019-07-10 21:25
it's now released! https://github.com/xcp-ng/xenadmin/releases/tag/v8.0.1.26
