### ISSUE TITLE
XCP-NG Center Windows 10 pro graphical bug AND XenCenter too

### ISSUE THREAD

**Issue by TheDevilDan** [xcp-ng/xenadmin#119] opened 2018-11-10 15:50 UTC
Hi,

I installed XenCenter And XCP-NG Center on 2 computer. One virtual machine, and one computer. These computers has new install of windows 10 pro 1803 with updates.

When I open WenCenter or XCP-NG center, I haven't the colors on the application.

I attach the normal screen of XCP-NG center, and a screen of XCP-NG center on new computer without the colors. I didn't find the solution, .Net Framework is included apparently in 1803 (V4.7.2)...

I haven't color in all the menu, no relief, like a "classic theme" of windows.

Bug version of XCP-NG center : (XenCenter too)
![xcp-bug01](https://user-images.githubusercontent.com/33637125/48303282-ad9c4980-e508-11e8-83cc-cd9765722790.PNG)

Good version on an older install of Windows 10 :
![xcp-normal](https://user-images.githubusercontent.com/33637125/48303281-ad9c4980-e508-11e8-90c8-1849598d9b65.PNG)

If you have an idea, i am running !!

topic reffered : https://xcp-ng.org/forum/topic/607/xcp-ng-center-windows-10-pro-graphical-bug-and-xencenter-too

**Comment by borzel** [comment] 2018-11-10 16:18
should be relatet to https://github.com/xenserver/xenadmin/commit/4a70c327869bc868625b31242a550183d4e13770

**Comment by borzel** [comment] 2018-11-10 16:29
confirmed!

**Comment by TheDevilDan** [comment] 2018-11-10 16:40
Confirmed, you have the bug now ?

**Comment by borzel** [comment] 2018-11-10 16:46
Bug fixed with patch from Citrix: https://github.com/xcp-ng/xenadmin/commit/719c1be0bfeeb206da163438a920a3ff0ddcd54b

**Comment by TheDevilDan** [comment] 2018-11-10 16:49
How can we apply this patch ?

**Closed** 2018-11-10 16:48 UTC
Labels: bug, solution found

**Comment by borzel** [comment] 2018-11-10 16:54
just wait for the XCP-ng Center 7.6.1 release... I'm currently building ... should be out within the next hour.

**Comment by TheDevilDan** [comment] 2018-11-10 17:00
Cool ! Thank you for your quickly actions !!!

**Comment by borzel** [comment] 2018-11-10 17:11
Was just luck, because I spotted the commit yesterday in the Citrix commit list.

**Comment by TheDevilDan** [comment] 2018-11-10 17:19
Thanks, it works, perfectly !! Thank you very much for your quick fixes !!!!

**Comment by borzel** [comment] 2018-11-10 21:48
oh thanks! that was a typo... changed it
