### ISSUE TITLE
Add Force checkbox to Live Migrate Dialog

### ISSUE THREAD

**Issue by igerlster** [xcp-ng/xenadmin#66] opened 2018-05-22 21:43 UTC
Hi,

live migration from e.g. xeon v3 to xeon v4 fails because of cpu mismatch.. xe vm-migrate command line with force it mostly works fine...

Maybe a "Force Live Migration" Checkbox could be added ?

Thanks
Sebastian

**Comment by olivierlambert** [comment] 2018-05-22 21:59
It is doing a force migration by default (without force, it would be refused). We use basically the same API calls than what you did in CLI.

**Comment by igerlster** [comment] 2018-05-22 22:33
Oh.. i only tested it on XenSever and thought it would be the same...

Thanks !

**Comment by olivierlambert** [comment] 2018-05-22 22:45
Oh sorry misread your request: you mean you **can't** force it in XCP-ng Center?

**Comment by igerlster** [comment] 2018-05-23 13:55
On XenServer Center i HAVE to use the command line since GUI doesn't have a force button... if XCP-ng Center uses force by default it should be fine...

**Comment by olivierlambert** [comment] 2018-05-23 22:02
Okay I was confused: it was late and I think you asked for Xen Orchestra UI! In Xen Orchestra, we force it by default.

In XenCenter, it's likely that's it's NOT forced by default (hence your experience with it) and indeed, if you don't see a force checkbox, it's not exposed.

@borzel This is probably something you could add and push against mainline too ;)

**Comment by borzel** [comment] 2018-07-11 21:14
@igerlster Can you provide a bit more context? Are you livemigrating in a pool or from host to host? Are you using the migration wizard? Can you maybe post a screenshot?

At this stage it's not clear to me, what you are exactly doing.

I looked into XCP-ng Center source code, but was not able to find the migration code or the mechanic to trigger a migration. It's a bit undocumented :-/

**Comment by borzel** [comment] 2018-07-11 22:14
@igerlster I managed to find the migration code, can you please test this fix: https://builds.schulzalex.de/xcp-ng/fix-migrate-with-force

**Comment by igerlster** [comment] 2018-07-13 10:54
Hi,
Sorry for my late reply.

unfortunately no success, i'm trying to migrate a vm from XeonE3 to slightly different XeonE3 and get CPU mismatch. Using force on the command line works fine. And it shouldn't be a problem most of the time since the only feature missing is a on chip gpu.

https://i.imgur.com/DMRnCOD.png

If this Dialog would give a warning "CPU mismatch, force live migrate ?" that would be very nice :-)

Thanks,

**Comment by borzel** [comment] 2018-07-13 13:21
Can you please provide the title of the dialog? Its a generic copy wizard which has many modes. I'll try to find your specific issue first :-)

**Comment by igerlster** [comment] 2018-07-13 13:32
Sure : right click on a VM -> Migrate to Sever -> Migrate VM wizard... -> Dialog with Name "Migrate VM" opens

:-)

**Comment by borzel** [comment] 2018-07-13 14:24
Are you livemigrating in a pool or from host to host?

**Comment by borzel** [comment] 2018-07-13 14:37
Ok, wish me luck... Maybe this weekend I have another testversion *hack* *modify* *build*

**Comment by igerlster** [comment] 2018-07-13 15:08
OK :-) nice .-) Good luck !

**Comment by borzel** [comment] 2018-07-14 20:30
I did look deeper into this ... it's complicated...

The wizard ask's the server, wether it can migrate the vm:

![grafik](https://user-images.githubusercontent.com/5782951/42728175-ac2baeda-87b4-11e8-8090-20bddd091e08.png)

hmm....

**Comment by igerlster** [comment] 2018-07-14 20:39
hmm. maybe you can add "force=true" in options ? so the answer the server gives should be "yes"... maybe :-)

**Comment by borzel** [comment] 2018-07-14 21:00
good hint... I did not see this parameter 🙈

**Comment by igerlster** [comment] 2018-07-14 21:31
Oh wow .. Nice :)

**Comment by igerlster** [comment] 2018-07-14 21:34
Now passing force to the the part of the code asking if migrate is possible ... Hmm...

**Comment by borzel** [comment] 2018-07-14 21:36
buildserver is allready building

**Comment by borzel** [comment] 2018-07-14 21:41
Please carefully check with this build: https://builds.schulzalex.de/xcp-ng/fix-migrate-with-force/
Id did just implement the checking, the actual migration may fail. Please test not with system in production. Test with VMs of which you have a backup!

**Comment by igerlster** [comment] 2018-07-14 22:11
Oh nice, thanks! :-) now i get the option to start the migration. So seems to be working. I don't have any non production systems right now to test if migration would start :-(

**Comment by borzel** [comment] 2018-07-14 22:22
I even don't have production systems with this scenario, so I'm not able to test too :-(

**Comment by borzel** [comment] 2018-07-14 22:22
!Call to the world!
Please can someone test on non production systems?

**Comment by skajter** [comment] 2018-07-16 08:47
I have two servers that have 'similar' CPU, and have that problem, so i can't move VMs live ... from one server to another, only solution was to shutdown VM, move and then run again.

Error (or more warning), was showing that server CPU don't have features on remote ... where both server have Intel i5 cpus - only difference is generation ;)

Installed your nightly version, and can confirm that moving VM is possible now! Thanks, have no idea what is changed, but is possible to move from one server to another - on live session.

**Comment by skajter** [comment] 2018-07-16 09:04
After further testing ... is not that easy as i was think, some VM failed to move:

> "Failed","Migrating VM 'TSCScripts' from 'tsc-xenserver' to 'xenserver'
Internal error: Xenops_interface.Internal_error("(Unix.Unix_error \"Connection reset by peer\" write \"\")")
Time: 00:08:12","xenserver","Jul 16, 2018 9:45 AM"

**Comment by borzel** [comment] 2018-07-16 21:39
I added another menu item to "Force Migrate" VMs:

![grafik](https://user-images.githubusercontent.com/5782951/42785082-6ac2b576-8951-11e8-9844-e8ff0b22a2ac.png)


please try again with build 99.99.99.36
https://builds.schulzalex.de/xcp-ng/fix-migrate-with-force/

**Comment by skajter** [comment] 2018-07-17 09:01
> "Failed","Migrating VM 'Scripts' from 'two-xenserver' to 'xenserver'
Internal error: Xenops_interface.Internal_error("(Unix.Unix_error \"Connection reset by peer\" write \"\")")
Time: 00:08:02","xenserver","Jul 17, 2018 9:18 AM"

Nope ;) - Force flag for some reason not working :/ - when i was try to migrate in 'normal' way have same result.

Only difference that i notice is 'progress bar' in events ... first (attempt) was when migrate vm, and that was fine, then progress was reset to 0, then i believe was try to startup vm? So progress is moving, and then failure message appear.

With one is weird anyway, as i can migrate easily from 'xenserver' to 'two-xenserver'

`[root@xenserver ~]# xe host-cpu-info
cpu_count       : 8
    socket_count: 1
          vendor: GenuineIntel
           speed: 2793.074
       modelname: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
          family: 6
           model: 30
        stepping: 5
           flags: fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ht syscall nx lm constant_tsc arch_perfmon rep_good nopl nonstop_tsc pni monitor est ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm ida dtherm
        features: 0098e3fd-bfebfbff-00000001-28100800
     features_pv: 17c9cbf5-80b82201-2191cbf5-00000003-00000000-00000000-00000000-00000000-00000000-00000000
    features_hvm: 17cbfbff-80b82221-2993fbff-00000003-00000000-00000000-00000000-00000000-00000000-00000000


[root@xenserver ~]#`

`[root@two-xenserver ~]# xe host-cpu-info
cpu_count       : 8
    socket_count: 1
          vendor: GenuineIntel
           speed: 3591.766
       modelname: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
          family: 6
           model: 60
        stepping: 3
           flags: fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ht syscall nx lm constant_tsc arch_perfmon rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq monitor est ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm ida arat epb pln pts dtherm fsgsbase bmi1 avx2 bmi2 erms xsaveopt
        features: 7ffafbff-bfebfbff-00000021-2c100800
     features_pv: 17c9cbf5-f6f83203-2191cbf5-00000023-00000001-00000329-00000000-00000000-00000000-00000000
    features_hvm: 17cbfbff-f7fa3223-2d93fbff-00000023-00000001-000007ab-00000000-00000000-00000000-00000000


[root@two-xenserver ~]#`

PS: Sorry it was i7, i was think that they are i5 ;)

**Comment by skajter** [comment] 2018-07-17 09:07
So in short, i can move vm up in cpu features (stepping)? and cannot be downgraded? I mean when run vm on better cpu, you cannot be moved on worst one?

**Comment by borzel** [comment] 2018-07-17 09:11
That's the allways the case if you use single Servers with different CPU's.

If you build a pool from your single Servers, the CPU-features are used from the "worst" CPU; but some CPU's don't have the masking feature so even this isn't possible.

(In my option the live migration from host to host (outside a pool) should only be needed in migration/maintenance scenarios.)

**Comment by skajter** [comment] 2018-07-17 09:52
Well i have only two servers, and i use them to move on server maintenance, and on balancing resources.

I will try to create pool and migrate vm's between servers in one pool, to have look that will work, as i was never try before.

**Comment by borzel** [comment] 2018-07-25 21:37
to sum up, you can now migrate with XCP-ng Center the same way like with cli-commands?
So the issue is resolved with my changes?

**Comment by cometmth** [comment] 2018-07-25 23:17
Based on my understanding of the issue, I think it's resolved.  My test environment has an i3-4130 and an i7-3370. Llive migrating from the newer i3 to the older i7 required using the new 'Force Migrate VM wizard...'  The regular migration wizard was showing the "..does not have some of the CPU features..." message in this direction.  The live migration was successful.  I was able to migrate back from the i7 to the i3 using the standard migrate wizard.  

The i3 is in a pool by itself (only member), and the i7 is a standalone server.  Both are on xcp-ng 7.4.  I tested with xcp-ng center linked above (https://builds.schulzalex.de/xcp-ng/fix-migrate-with-force/)

**Closed** 2018-07-26 19:37 UTC
Labels: do PR to upstream, enhancement, help wanted, in progress :running_man:

**Comment by dynamyc010** [comment] 2025-10-30 13:39
Hey there! 

I found this issue and the button seems to have disappeared at some point when upstream code got pulled in? 

Can we get this working again at some point? Xen Orchestra gives an option to just push through the CPU features warning, but this grays the whole pool out, leaving me unable to migrate VMs, even though I know the new pool has MORE features and is otherwise compatible. And Xen Orchestra gets a bit mad in certain situations, so I'd prefer to use XCP-ng Center.
